spring:
  profiles:
    active: dev
---
server:
  port: 8001
mybatis:
  type-aliases-package: com.zeph.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  profiles: dev
  application:
    name: springcloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db3?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: "zeph"
# Eureka配置：配置服务注册中心地址

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:7001/eureka/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: springcloud-provider-dept-8001
    prefer-ip-address: true
#info配置
info:
  app.name: zeph-springcloud
  #项目的名称
  company.name: blog.zeph.com
  #公司的名称
---
server:
  port: 8001
mybatis:
  type-aliases-package: com.zeph.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  profiles: test
  application:
    name: springcloud-config-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db02?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: "zeph"
# Eureka配置：配置服务注册中心地址

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:7001/eureka/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: springcloud-provider-dept8001
    prefer-ip-address: true
#info配置
info:
  app.name: zeph-springcloud
  #项目的名称
  company.name: blog.zeph.com
  #公司的名称
