spring:
  profiles:
    active: dev
---
server:
  port: 7001

#spring配置
spring:
  profiles: dev
  application: 
    name: springcloud-config-eureka
#Eureka配置
eureka:
  instance:
    hostname: eureka7001.com
    #Eureka服务端的实例名字
  client:
    register-with-eureka: false
    #表示是否向 Eureka 注册中心注册自己(这个模块本身是服务器,所以不需要)
    fetch-registry: false
    #如果为false,则表示自己为注册中心
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
---
#spring配置
spring:
  profiles: test
  application: 
    name: springcloud-config-eureka
#Eureka配置
eureka:
  instance:
    hostname: eureka7001.com
    #Eureka服务端的实例名字
  client:
    register-with-eureka: false
    #表示是否向 Eureka 注册中心注册自己(这个模块本身是服务器,所以不需要)
    fetch-registry: false
    #如果为false,则表示自己为注册中心
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      
